version: "3.8"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-20.04
    container_name: sql-server
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
